--- #YAML:1.0
name:                DBD-Ingres
version:             0.53
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Config:                        0
    DBI:                           1
    Getopt::Long:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
